plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Max: 125

Naming/MethodParameterName:
  AllowedNames:
    - x
    - y

Naming/VariableNumber:
  EnforcedStyle: snake_case
  AllowedIdentifiers:
    - exp2
    - log2
    - log10

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
